### PR TITLE
add ability to skipMainFeed connection

### PR DESCRIPTION
**Pull request by mixmix**
## Background

`ssb-tribes2` test suite was taking 3min 40s to run on my desktop. I did a little analysis and found that there was sometimes significant slow-downs calling `ssb.metafeeds.findOrCreate` , in particular the `ssb.tribes.start()` seems to take 3 seconds to complete (and it creates locks).

## Improvement

I noticed that unless we were testing persistence, setting up the `main` feed (publishing the rootMetaFeedId, and setting the `main` feed up in a shard...) is slow, and not actually useful for most tests.

I experimented with extracting that step and making it possible to turn it off.

### CODE REVIEW

**Comment by mixmix** [comment]
Here it is in `ssb-tribes2`

**Comment by staltz** [comment]
Profiling shows that it takes about 500ms to announce the root on the main, but it takes 1600ms to create `/root/v1/:shard/main`.

**Comment by staltz** [comment]
I think all of these waits are coming from lodash.debounce which is sprinkled around in ssb-db2 and async-append-only-log. In some tests we have disabled those timers so that tests run quicker.

**Comment by staltz** [comment]
Can we close this PR? @mixmix

**Pull request closed without merging**
